<?php

use Illuminate\Database\Seeder;

class OptionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('options')->delete();
        
        \DB::table('options')->insert(array (
            0 => 
            array (
                'id' => 1,
                'padre' => NULL,
                'nombre' => 'Admin',
                'ruta' => NULL,
                'descripcion' => 'Opciones de administración',
                'icono_l' => 'fa-folder',
                'icono_r' => 'fa-angle-left',
                'orden' => 0,
                'created_at' => '2017-04-09 21:53:18',
                'updated_at' => '2017-04-13 18:54:56',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'padre' => 1,
                'nombre' => 'Usuarios',
                'ruta' => 'admin/user',
                'descripcion' => 'Administración de usuarios',
                'icono_l' => 'fa-circle-o',
                'icono_r' => '',
                'orden' => 3,
                'created_at' => '2017-04-09 21:53:18',
                'updated_at' => '2017-04-13 18:54:56',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'padre' => 1,
                'nombre' => 'Opciones',
                'ruta' => 'admin/option',
                'descripcion' => 'Administración de las opciones del menu',
                'icono_l' => 'fa-circle-o',
                'icono_r' => '',
                'orden' => 1,
                'created_at' => '2017-04-09 21:53:18',
                'updated_at' => '2017-04-13 18:54:56',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'padre' => 1,
                'nombre' => 'Roles',
                'ruta' => 'admin/rols',
                'descripcion' => 'Administración de los roles de los usuarios',
                'icono_l' => 'fa-circle-o',
                'icono_r' => '',
                'orden' => 2,
                'created_at' => '2017-04-09 21:53:18',
                'updated_at' => '2017-04-13 18:54:56',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'padre' => NULL,
                'nombre' => 'Inventario',
                'ruta' => NULL,
                'descripcion' => '',
                'icono_l' => 'fa-th',
                'icono_r' => 'fa-angle-left',
                'orden' => 4,
                'created_at' => '2017-04-09 21:53:18',
                'updated_at' => '2017-04-13 18:54:56',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'padre' => 5,
                'nombre' => 'Categorías',
                'ruta' => 'inventario/icategorias',
                'descripcion' => 'Administración de las categorías de los articulos',
                'icono_l' => 'fa-circle-o',
                'icono_r' => '',
                'orden' => 5,
                'created_at' => '2017-04-09 21:53:18',
                'updated_at' => '2017-04-13 18:54:56',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'padre' => 5,
                'nombre' => 'Artículos',
                'ruta' => 'inventario/items',
                'descripcion' => 'Administración de los artículos',
                'icono_l' => 'fa-circle-o',
                'icono_r' => '',
                'orden' => 6,
                'created_at' => '2017-04-09 21:53:18',
                'updated_at' => '2017-04-13 18:54:56',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'padre' => 5,
                'nombre' => 'Unidades de medida',
                'ruta' => 'inventario/unimeds',
                'descripcion' => 'Administración de las unidades de medida',
                'icono_l' => 'fa-circle-o',
                'icono_r' => '',
                'orden' => 7,
                'created_at' => '2017-04-09 21:53:18',
                'updated_at' => '2017-04-13 18:54:56',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'padre' => 5,
                'nombre' => 'Estados de articulos',
                'ruta' => 'inventario/iestados',
                'descripcion' => 'Administración de las unidades de medida',
                'icono_l' => 'fa-circle-o',
                'icono_r' => '',
                'orden' => 8,
                'created_at' => '2017-04-09 21:53:18',
                'updated_at' => '2017-04-13 18:54:56',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'padre' => NULL,
                'nombre' => 'Compras',
                'ruta' => NULL,
                'descripcion' => '',
                'icono_l' => 'fa-shopping-cart',
                'icono_r' => 'fa-angle-left',
                'orden' => 9,
                'created_at' => '2017-04-09 21:53:18',
                'updated_at' => '2017-04-13 18:49:47',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'padre' => 10,
                'nombre' => 'Listado',
                'ruta' => 'compras/compras',
                'descripcion' => 'Ingresos de artículos a inventario',
                'icono_l' => 'fa fa-circle-o',
                'icono_r' => NULL,
                'orden' => 1,
                'created_at' => '2017-04-09 21:53:18',
                'updated_at' => '2017-04-14 09:38:19',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'padre' => 10,
                'nombre' => 'Proveedores',
                'ruta' => 'compras/proveedores',
                'descripcion' => 'Administración de proveedores',
                'icono_l' => 'fa-circle-o',
                'icono_r' => '',
                'orden' => 2,
                'created_at' => '2017-04-09 21:53:18',
                'updated_at' => '2017-04-14 09:36:56',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'padre' => 10,
                'nombre' => 'Estados',
                'ruta' => 'compras/cestados',
                'descripcion' => 'Administración de estados de las compras',
                'icono_l' => 'fa-circle-o',
                'icono_r' => '',
                'orden' => 3,
                'created_at' => '2017-04-09 21:53:19',
                'updated_at' => '2017-04-14 09:36:56',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'padre' => 10,
                'nombre' => 'Tipo de comprobantes',
                'ruta' => 'compras/tcomprobantes',
                'descripcion' => '',
                'icono_l' => 'fa-circle-o',
                'icono_r' => '',
                'orden' => 4,
                'created_at' => '2017-04-09 21:53:19',
                'updated_at' => '2017-04-14 09:36:56',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'padre' => NULL,
                'nombre' => 'Ventas',
                'ruta' => NULL,
                'descripcion' => '',
                'icono_l' => 'fa-laptop',
                'icono_r' => 'fa-angle-left',
                'orden' => 15,
                'created_at' => '2017-04-09 21:53:19',
                'updated_at' => '2017-04-13 18:49:47',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'padre' => 15,
                'nombre' => 'Listado',
                'ruta' => 'ventas/ventas',
                'descripcion' => NULL,
                'icono_l' => 'fa fa-circle-o',
                'icono_r' => NULL,
                'orden' => 16,
                'created_at' => '2017-04-09 21:53:19',
                'updated_at' => '2017-04-15 16:42:44',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'padre' => 15,
                'nombre' => 'Estados',
                'ruta' => 'ventas/vestados',
                'descripcion' => '',
                'icono_l' => 'fa-circle-o',
                'icono_r' => '',
                'orden' => 17,
                'created_at' => '2017-04-09 21:53:19',
                'updated_at' => '2017-04-13 18:49:48',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'padre' => 15,
                'nombre' => 'Clientes',
                'ruta' => 'ventas/clientes',
                'descripcion' => '',
                'icono_l' => 'fa-circle-o',
                'icono_r' => '',
                'orden' => 18,
                'created_at' => '2017-04-09 21:53:19',
                'updated_at' => '2017-04-13 18:49:48',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'padre' => NULL,
                'nombre' => 'Medicamentos',
                'ruta' => NULL,
                'descripcion' => '',
                'icono_l' => 'fa-ambulance',
                'icono_r' => 'fa-angle-left',
                'orden' => 19,
                'created_at' => '2017-04-09 21:53:19',
                'updated_at' => '2017-04-13 18:49:48',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'padre' => 19,
                'nombre' => 'Laboratorios',
                'ruta' => 'medicamentos/laboratorios',
                'descripcion' => '',
                'icono_l' => 'fa-circle-o',
                'icono_r' => '',
                'orden' => 20,
                'created_at' => '2017-04-09 21:53:19',
                'updated_at' => '2017-04-13 18:49:48',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'padre' => 19,
                'nombre' => 'Categorías',
                'ruta' => 'medicamentos/fcategorias',
                'descripcion' => '',
                'icono_l' => 'fa-circle-o',
                'icono_r' => '',
                'orden' => 21,
                'created_at' => '2017-04-09 21:53:19',
                'updated_at' => '2017-04-13 18:49:48',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'padre' => 19,
                'nombre' => 'Farmacos',
                'ruta' => 'medicamentos/farmacos',
                'descripcion' => '',
                'icono_l' => 'fa-circle-o',
                'icono_r' => '',
                'orden' => 22,
                'created_at' => '2017-04-09 21:53:19',
                'updated_at' => '2017-04-13 18:49:48',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'padre' => 19,
                'nombre' => 'Medicamentos',
                'ruta' => 'medicamentos/medicamentos',
                'descripcion' => '',
                'icono_l' => 'fa-circle-o',
                'icono_r' => '',
                'orden' => 23,
                'created_at' => '2017-04-09 21:53:19',
                'updated_at' => '2017-04-13 18:49:48',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'padre' => NULL,
                'nombre' => 'Ayuda',
                'ruta' => NULL,
                'descripcion' => 'Manual de usuario y tutoriales',
                'icono_l' => 'fa-plus-square',
                'icono_r' => '',
                'orden' => 24,
                'created_at' => '2017-04-09 21:53:19',
                'updated_at' => '2017-04-13 18:49:48',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'padre' => NULL,
                'nombre' => 'Acerca De...',
                'ruta' => NULL,
                'descripcion' => '',
                'icono_l' => 'fa-info-circle',
                'icono_r' => '',
                'orden' => 25,
                'created_at' => '2017-04-09 21:53:19',
                'updated_at' => '2017-04-13 18:49:48',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'padre' => 10,
                'nombre' => 'Nueva',
                'ruta' => 'compras/compras/create',
                'descripcion' => 'Registro de nueva compra',
                'icono_l' => 'fa fa-circle-o',
                'icono_r' => NULL,
                'orden' => 0,
                'created_at' => '2017-04-13 16:39:13',
                'updated_at' => '2017-04-14 09:36:56',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'padre' => 2,
                'nombre' => 'nueva2',
                'ruta' => NULL,
                'descripcion' => NULL,
                'icono_l' => 'fa fa-circle-o',
                'icono_r' => NULL,
                'orden' => 0,
                'created_at' => '2017-04-13 17:08:58',
                'updated_at' => '2017-04-13 17:54:31',
                'deleted_at' => '2017-04-13 17:54:31',
            ),
            27 => 
            array (
                'id' => 28,
                'padre' => 15,
                'nombre' => 'Nueva',
                'ruta' => 'ventas/ventas/create',
                'descripcion' => 'Realizar nueva venta',
                'icono_l' => 'fa fa-circle-o',
                'icono_r' => NULL,
                'orden' => 0,
                'created_at' => '2017-04-15 16:38:52',
                'updated_at' => '2017-04-15 16:39:27',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'padre' => 1,
                'nombre' => 'Horarios',
                'ruta' => 'admin/horarios',
                'descripcion' => 'Horarios de atencion',
                'icono_l' => 'fa fa-circle-o',
                'icono_r' => NULL,
                'orden' => 0,
                'created_at' => '2017-04-21 11:15:22',
                'updated_at' => '2017-04-21 11:15:22',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}